/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8bd732c4-283b-4fa7-ad52-dd9ad6ad79cd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SYA1e1PcU",
    "aws_user_pools_web_client_id": "2mqgf0ui1im36690qga26b4hlu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hde4nydzwbas5dslcgnsjkmfii.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4hwcpyg6wffcpki3pfprm5adga"
};


export default awsmobile;
